# List of copypastas shown when entering the '!shitscord copypasta list' command
cpnames = ["navyseals", "buzzwords", "nicejoke", "navyfurs", "navyknights", "navyswag", "navykindergarten", "weeb", ]

# copypastas themselves, with the exact same name as in cpnames list
cplist = [
    "What the fuck did you just fucking say about me, you little bitch? I’ll have you know I graduated top of my "
    "class in the Navy Seals, and I’ve been involved in numerous secret raids on Al-Quaeda, and I have over 300 "
    "confirmed kills. I am trained in gorilla warfare and I’m the top sniper in the entire US armed forces. You are "
    "nothing to me but just another target. I will wipe you the fuck out with precision the likes of which has never "
    "been seen before on this Earth, mark my fucking words. You think you can get away with saying that shit to me "
    "over the Internet? Think again, fucker. As we speak I am contacting my secret network of spies across theUSA and "
    "your IP is being traced right now so you better prepare for the storm, maggot. The storm that wipes out the "
    "pathetic little thing you call your life. You’re fucking dead, kid. I can be anywhere, anytime, and I can kill "
    "you in over seven hundred ways, and that’s just with my bare hands. Not only am I extensively trained in unarmed "
    "combat, but I have access to the entire arsenal of the United States Marine Corps and I will use it to its full "
    "extent to wipe your miserable ass off the face of the continent, you little shit. If only you could have known "
    "what unholy retribution your little “clever” comment was about to bring down upon you, maybe you would have held "
    "your fucking tongue. But you couldn’t, you didn’t, and now you’re paying the price, you goddamn idiot. I will "
    "shit fury all over you and you will drown in it. You’re fucking dead, kiddo.",
    "As part of our review of narrative, we have decided to move forward with high level sustainability. Skate to "
    "where the puck is going to be.This sector has intuitive vector. Skate to where the puck is going to be.Going "
    "forward, the marketplace has changed. Incentivize horizontally or future-proof.Taper the visibility "
    "horizontally. It is what it is.Our visibility center is focused on new ways to synthesize the consumer space "
    "through multiplatform deployments of low-hanging fruit.Next quarter we will launch our new narrative-killer "
    "which will dialog the optics horizontally.",
    "I sexually Identify as an unoriginal joke. Ever since I was a boy I dreamed of surfing reddit dropping shitposts "
    "and derailing actual conversation. People say to me that this has been really going on for far too long and and "
    "it trivialises gender identity but I don’t care, I'm a massive asshole. I’m having a plastic surgeon install a "
    "mountain dew dispenser, a catheter and and a poop shoot on my body. From now on I want you guys to call me "
    "“Logical Gamer” and respect my right to freeze peach. If you can’t accept me you’re a god damn tumblirina sjw "
    "cultural marxist liberal and you triggered lol?. Thank you for being so understanding.",
    "What the fuck did you just fucking say about me, you little bitch? I’ll have you know I reached the top of the "
    "page on FurAffinity, and I’ve been involved in numerous secret conventions worldwide, and I have over 300 "
    "confirmed yiffs. I am trained in gorilla fursuiting and I’m the top suiter in the entire US furry fandom. You "
    "are nothing to me but just another weeaboo. I will yiff the fuck out of you with precision the likes of which "
    "has never been seen before on this Earth, mark my fucking words. You think you can get away with saying that "
    "shit to me over the Internet? Think again, fucker. As we speak I am contacting my secret network of artists "
    "across all of FA and your name is being added to Artist Beware right now so you better prepare for the storm, "
    "weeb. The storm that wipes out the pathetic little thing you call your customer base. You’re fucking done, "
    "kid. I can be anywhere, anytime, and I can yiff you in over seven hundred ways, and that’s just with my bare "
    "paws. Not only am I extensively trained in unprotected sex, but I have access to the entire collection of the "
    "cub porn you've drawn and I will use it to its full extent to wipe your miserable ass off the face of FA, "
    "you little shit. If only you could have known what unholy retribution your little “clever” comment was about to "
    "bring down upon you, maybe you would have held your fucking tongue. But you couldn’t, you didn’t, and now you’re "
    "paying the price, you goddamn idiot. I will shit furries all over you and you will drown in them. You’re fucking "
    "done, kiddo.",
    "What the flip did thee just flipping gabble about me, thine miniscule bitch? I’ll have thee know I bested the "
    "most prestigious jousting class in the whole of Camelot, and I hath been involved in numerous secret marches on "
    "behalf of his Majesty, King Arthur, and I hath over 300 confirmed victories on horseback. I am trained in castle "
    "of Guerrilla warfare and I am indeed the highest ranking joustee in the entire land of Great Britannia. Thee are "
    "nothing to me but another false crossbearer. I will joust thine shambles with precision the likes of which hath "
    "never been observed in the King’s lands, mark my flipping words! Thou think thou can escape retribution by "
    "shouting that hogwash at me from afar? I implore thee to think again, peasant. As we converse I am contacting my "
    "secretive network of knights across the realm and thine footsteps are being traced right now, so thou best "
    "prepare thineself for the storm, pig-maggot! The storm that wipes out the pathetic little thing thou call your "
    "armour. Thou art a flipping dead man. I can be anywhere, anytime, and I can kill thou in over seven hundred "
    "ways, and that’s just with my bare lance. Not only am I extensively trained in mounted combat, but I hath access "
    "to the entire arsenal of the Kings Royal Army, and I shall use it to its full extent to wipe your miserable "
    "derriere off the face of the realm, thou miniscule feaces. If only thou could have foreseen what unholy "
    "retribution your little “clever” challenge was about to bring down upon thee, maybe thou would have held thee "
    "flipping tongue. But thou couldn’t, thou didn’t, and now thee art paying the price, you goddamn fool. I shall "
    "shit fury all over thou britches and thee will drown in it. Thou art flipping dead, child.",
    "What the swag did you just fucking yolo about me, you little wayne? I'll have you know I graduated top of my "
    "class in the SwagFags, and I've been involved in numerous Obey Records , and I have over 300 confirmed Swaggers. "
    "I am trained in wearing snapbacks and I'm the top poser in the entire Swagfag Army. You are nothing to me but "
    "just another No swag. I will swag you the fuck out with swagger the likes of which has never been seen before on "
    "this Earth, mark my fucking hashtags. You think you can get away with not taking pictures in the mirror over the "
    "Internet? Think again, fucker. As we speak I am contacting my mom, she has alot of swag, and your ratchet ass is "
    "being traced right now so you better prepare for the yolo, nigga. The yolo that wipes out the pathetic little "
    "thing you call your swag. You're fucking dead, nigga. I can swag anywhere, anytime, and I can swag in over seven "
    "hundred ways, and that's just with my swaggy baggy skinny jeans. Not only am I extensively trained in having "
    "plugs and snake bites, but I have access to the entire Hollister store. and I will use it to its full swagginess "
    "to wipe your miserable swag off the face of tumblr, you little Non-trend follower. I will swag yolo all over you "
    "and you will swag in it. You're fucking dead, nigga",
    "What the heck did you just flipping say about me, you big meanie? I'll have you know I graduated top of my class "
    "in the Tiny Tots Program, and I've been involved in numerous secret raids on the girl's bathroom, and I have "
    "over 300 confirmed noogies. I am trained in Nerf warfare and I have the most gold stars in the entire "
    "kindergarten class. You are nothing to me but just another butthead. I will beat you the heck up with precision "
    "the likes of which has never been seen before on this Earth, mark my dang words. You think you can get away with "
    "saying that baloney to me on the glowy type-box? Think again, doodiehead. As we speak I am contacting my secret "
    "network of teachers across the USA and your parents are being called to pick you up right now so you better "
    "prepare for the spanking, junior. The spanking that wipes out the dumb little thing you call your playtime. "
    "You're in big darn trouble, kid. I can be anywhere, anytime, and I can wedgie you in over seven hundred ways, "
    "and that's just with my bare hands. Not only am I extensively trained in unarmed fartfights, but I have access "
    "to the entire arsenal of the United States PTA and I will use it to its full extent to wipe your dorky bottom "
    "off the face of the playground, you little poopypants. If only you could have known what serious punishments "
    "your little 'smartypants' comment was about to bring down upon you, maybe you would have held your goshdarned "
    "tongue. But you couldn't, you didn't, and now you're paying the price, you silly doofus. I will spray boogers "
    "all over you and you will cry about it. You're frickin grounded, buttmunch.",
    "Nani the fuck did you just fucking iimasu about watashi, you chiisai bitch desuka? Watashi’ll have anata know "
    "that watashi graduated top of my class in Nihongo 3, and watashi’ve been involved in iroirona Nihongo tutoring "
    "sessions, and watashi have over sanbyaku perfect test scores. Watashi am trained in kanji, and watashi is the "
    "top letter writer in all of southern California. Anata are nothing to watashi but just another weaboo. Watashi "
    "will korosu anata the fuck out with vocabulary the likes of which has never been mimasu’d before on this "
    "continent, mark watashino fucking words. Anata thinks anata can get away with hanashimasing that kuso to watashi "
    "over the intaaneto? Omou again, fucker. As we hanashimasu, watashi am contacting watashino secret netto of "
    "otakus across the USA, and anatano IP is being traced right now so you better junbishimasu for the ame, "
    "ujimushi. The ame that korosu’s the pathetic chiisai thing anata calls anatano life. You’re fucking "
    "shinimashita’d, akachan.",
    ]
